version: '2'
services:


  ##################################################
  ##                    API                       ##
  ##################################################

  webapi-sienn:
    build: ./
    command: dotnet SIENN.WebApi.dll
    ports:
      - 8080:5000
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development


  ##################################################
  ##                DATABASES                     ##
  ##################################################

  one-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:        
       - POSTGRES_PASSWORD=SiennaPass#0Rd


  ##################################################
  ##                TOOLS                         ##
  ##################################################

  interface-postgres:
    image: fenglc/pgadmin4
    ports: 
      - 82:5050
    environment:
      DEFAULT_PASSWORD: SiennaPass#0Rd
      DEFAULT_USER: postgres
